package com.flightcomputer.control;

import com.flightcomputer.control.autotune.TuningResult;

/** Builds deterministic PID inputs from the live Sable vehicle instead of one global tune. */
public final class AdaptiveFlightTuner {
    private long lastFingerprint=Long.MIN_VALUE;
    public void update(VehicleState state,ThrusterRegistry registry,SixAxisStabilizer stabilise,SixAxisStabilizer cruise){if(state==null||registry==null||stabilise==null||cruise==null)return;long fingerprint=fingerprint(state,registry);if(fingerprint==lastFingerprint)return;lastFingerprint=fingerprint;stabilise.applyProfile(profile(state,registry,FlightMode.STABILIZE,true));cruise.applyProfile(profile(state,registry,FlightMode.CRUISE,false));}
    public long fingerprint(VehicleState state,ThrusterRegistry registry){long h=1469598103934665603L;h=mix(h,state.structureBlockCount/10);h=mix(h,Math.round(state.mass/10.0));h=mix(h,q(state.comX));h=mix(h,q(state.comY));h=mix(h,q(state.comZ));h=mix(h,q(state.inertiaPitch));h=mix(h,q(state.inertiaRoll));h=mix(h,q(state.inertiaYaw));h=mix(h,q(state.gravityAcceleration));for(FlightMode mode:FlightMode.values())for(VectorDirection d:VectorDirection.values()){h=mix(h,registry.getVectorThrusterCount(mode,d));h=mix(h,q(registry.getVectorAuthority(mode,d)));}return h;}
    private TuningResult profile(VehicleState s,ThrusterRegistry r,FlightMode mode,boolean stable){double mass=Math.max(1e-3,s.mass);double verticalAuthority=Math.min(r.getVectorAuthority(mode,VectorDirection.UP),r.getVectorAuthority(mode,VectorDirection.DOWN))/mass;double longitudinalAuthority=Math.min(r.getVectorAuthority(mode,VectorDirection.NORTH),r.getVectorAuthority(mode,VectorDirection.SOUTH))/mass;double lateralAuthority=Math.min(r.getVectorAuthority(mode,VectorDirection.EAST),r.getVectorAuthority(mode,VectorDirection.WEST))/mass;double pitchAuthority=torqueAuthority(r,mode,s,0)/Math.max(1e-3,s.inertiaPitch),rollAuthority=torqueAuthority(r,mode,s,2)/Math.max(1e-3,s.inertiaRoll),yawAuthority=torqueAuthority(r,mode,s,1)/Math.max(1e-3,s.inertiaYaw);double ps=responseScale(pitchAuthority,2),rs=responseScale(rollAuthority,2),ys=responseScale(yawAuthority,1.5),vs=responseScale(verticalAuthority,3),ls=responseScale(longitudinalAuthority,3),as=responseScale(lateralAuthority,3);double pm=Math.max(.5,pitchAuthority*.72),rm=Math.max(.5,rollAuthority*.72),ym=Math.max(.5,yawAuthority*.72),vm=Math.max(.5,verticalAuthority*.72),lm=Math.max(.5,longitudinalAuthority*.72),am=Math.max(.5,lateralAuthority*.72);double basePitch=stable?8:3.5,baseRoll=stable?8:3.5,baseYaw=stable?4.5:4,baseVertical=stable?3:3,baseLongitudinal=stable?2:2,baseLateral=stable?2:2;double baseI=stable?1:.7;return new TuningResult(g(basePitch*ps,.35*ps*.75*baseI,4*(1.12/ps),pm),g(baseRoll*rs,.35*rs*.75*baseI,4*(1.12/rs),rm),g(baseYaw*ys,.2*ys*.75*baseI,2*(1.10/ys),ym),g(baseVertical*vs,.6*vs*.70*baseI,1.2*(1.10/vs),vm),g(baseLongitudinal*ls,.2*ls*.70*baseI,.8*(1.10/ls),lm),g(baseLateral*as,.2*as*.70*baseI,.8*(1.10/as),am),fingerprint(s,r),2);}
    private static TuningResult.Gains g(double p,double i,double d,double max){return new TuningResult.Gains(clamp(p,.35,12),clamp(i,0,.75),clamp(d,.5,9),Math.max(.5,max));}
    private static double responseScale(double authority,double reference){if(!Double.isFinite(authority)||authority<=0)return .55;return clamp(Math.sqrt(authority/reference),.55,1.25);}
    private static double torqueAuthority(ThrusterRegistry registry,FlightMode mode,VehicleState state,int axis){double total=0;for(ThrusterLink link:registry.getAllLinks(mode)){if(link==null||link.source==null)continue;double thrust=Math.max(0,link.source.getAvailableThrust());if(thrust<=0)continue;double[] m=link.source.getMountOffset();if(m==null||m.length<3)continue;double rx=m[0]-state.comX,ry=m[1]-state.comY,rz=m[2]-state.comZ,fx=link.direction.x()*link.polarity*thrust,fy=link.direction.y()*link.polarity*thrust,fz=link.direction.z()*link.polarity*thrust,tx=ry*fz-rz*fy,tz=rx*fy-ry*fx,ty=rz*fx-rx*fz;total+=Math.abs(axis==0?tx:axis==1?ty:tz);}return total;}
    private static long q(double value){return Math.round(Double.isFinite(value)?value*1000:0);}private static long mix(long h,long value){h^=value;return h*1099511628211L;}private static double clamp(double v,double min,double max){return Math.max(min,Math.min(max,v));}
}
