package com.flightcomputer.control;

import com.flightcomputer.avionics.FlightControllerState;
import java.util.EnumMap;
import java.util.Map;

public final class FlightComputer {
    private final VehicleStateProvider stateProvider; private final ThrusterRegistry registry=new ThrusterRegistry();
    private final SixAxisStabilizer stabilizeStabilizer=new SixAxisStabilizer(true); private final SixAxisStabilizer cruiseStabilizer=new SixAxisStabilizer(); private final ThrustAllocator allocator=new ThrustAllocator(); private final MPCNavigator navigator; private FlightMode mode=FlightMode.STABILIZE;
    private double pitchStick,rollStick,yawRateStick,verticalStick,longitudinalStick,lateralStick; public double maxManualTiltRadians=Math.toRadians(25),maxManualYawRate=Math.toRadians(60),maxManualSpeed=6.0,cruiseMaxSpeed=20.0; public int replanIntervalTicks=4; private ControlAxis manualPulseAxis; private double manualPulseValue;
    private int ticksSinceReplan; private StabilizationSetpoint latestCruiseSetpoint=StabilizationSetpoint.hover(); private boolean altitudeHold,headingHold,positionHold,velocityHold; private boolean previousAltitudeHold,previousHeadingHold,previousPositionHold,previousVelocityHold; private double holdX,holdY,holdZ,holdYaw,holdVx,holdVy,holdVz,altitudeHoldTargetY=Double.NaN; private double lastCruiseLongitudinalVelocity,lastCruiseLateralVelocity,lastAppliedTargetX,lastAppliedTargetY,lastAppliedTargetZ; private boolean lastAppliedTargetValid;
    private VehicleState previousControlState; private int disturbanceRecoveryTicks; private static final int DISTURBANCE_RECOVERY_TICKS=10; private static final double DISTURBANCE_POSITION_DELTA=4.0,DISTURBANCE_SPEED_DELTA=12.0,DISTURBANCE_ANGULAR_RATE_DELTA=2.5,DISTURBANCE_ANGLE_DELTA=Math.toRadians(35.0); private static final double MAX_HOLD_VERTICAL_SPEED=1.5,HOLD_VERTICAL_P=0.15;
    public FlightComputer(VehicleStateProvider p,ObstacleSensor o){stateProvider=p;navigator=new MPCNavigator(o);} public FlightComputer(VehicleStateProvider p){this(p,null);} public ThrusterRegistry getRegistry(){return registry;} public ThrustAllocator getAllocator(){return allocator;} public MPCNavigator getNavigator(){return navigator;} public FlightMode getMode(){return mode;} public SixAxisStabilizer getStabilizeStabilizer(){return stabilizeStabilizer;} public SixAxisStabilizer getCruiseStabilizer(){return cruiseStabilizer;}
    public void setManualInput(double pitch,double roll,double yaw,double vertical,double longitudinal,double lateral){pitchStick=pitch;rollStick=roll;yawRateStick=yaw;verticalStick=vertical;longitudinalStick=longitudinal;lateralStick=lateral;} public void setManualPulse(ControlAxis axis,double value){if(axis==null||!Double.isFinite(value))return;manualPulseAxis=axis;manualPulseValue=Math.max(-0.65D,Math.min(0.65D,value));} public void setAltitudeHoldTarget(double y){altitudeHoldTargetY=Double.isFinite(y)?y:Double.NaN;}
    public void setNavigationTarget(double x,double y,double z){if(!Double.isFinite(x)||!Double.isFinite(y)||!Double.isFinite(z))return;boolean changed=!navigator.hasTarget()||Math.abs(navigator.targetX()-x)>1e-6||Math.abs(navigator.targetY()-y)>1e-6||Math.abs(navigator.targetZ()-z)>1e-6;navigator.setTarget(x,y,z);if(changed)resetCruiseGuidance();lastAppliedTargetX=x;lastAppliedTargetY=y;lastAppliedTargetZ=z;lastAppliedTargetValid=true;} public void clearNavigationTarget(){navigator.clearTarget();resetCruiseGuidance();lastAppliedTargetValid=false;} private void resetCruiseGuidance(){cruiseStabilizer.resetAll();ticksSinceReplan=0;lastCruiseLongitudinalVelocity=0;lastCruiseLateralVelocity=0;latestCruiseSetpoint=StabilizationSetpoint.hover();}
    private void synchronizeExternalTarget(){if(!navigator.hasTarget()){if(lastAppliedTargetValid){navigator.setTarget(lastAppliedTargetX,lastAppliedTargetY,lastAppliedTargetZ);resetCruiseGuidance();}return;}double x=navigator.targetX(),y=navigator.targetY(),z=navigator.targetZ();if(!lastAppliedTargetValid||Math.abs(lastAppliedTargetX-x)>1e-6||Math.abs(lastAppliedTargetY-y)>1e-6||Math.abs(lastAppliedTargetZ-z)>1e-6){resetCruiseGuidance();lastAppliedTargetX=x;lastAppliedTargetY=y;lastAppliedTargetZ=z;lastAppliedTargetValid=true;}}
    public void syncHolds(FlightControllerState s,VehicleState st){if(s==null||st==null)return;altitudeHold=s.altitudeHold();headingHold=s.headingHold();positionHold=s.positionHold();velocityHold=s.velocityHold();if(altitudeHold&&Double.isFinite(altitudeHoldTargetY))holdY=altitudeHoldTargetY;else if(altitudeHold&&!previousAltitudeHold)holdY=st.y;if(headingHold&&!previousHeadingHold)holdYaw=st.yaw;if(positionHold&&!previousPositionHold){holdX=st.x;holdY=st.y;holdZ=st.z;}if(velocityHold&&!previousVelocityHold){holdVx=st.vx;holdVy=st.vy;holdVz=st.vz;}previousAltitudeHold=altitudeHold;previousHeadingHold=headingHold;previousPositionHold=positionHold;previousVelocityHold=velocityHold;}
    public void engageCruise(double x,double y,double z){setNavigationTarget(x,y,z);mode=FlightMode.CRUISE;} public void disengageCruise(){mode=FlightMode.STABILIZE;clearNavigationTarget();} public double distanceToTarget(){VehicleState s=stateProvider.getState();return s!=null&&navigator.hasTarget()?navigator.distanceToTarget(s):-1;} public boolean isCruisePathBlocked(){return mode==FlightMode.CRUISE&&navigator.isPathBlocked();} public void tick(double dt){tick(dt,true,navigator.hasTarget());}
    public void tick(double dt,boolean stabiliserEnabled,boolean autopilotEnabled){VehicleState state=stateProvider.getState();if(state==null)return;if(detectPhysicsDisturbance(state))recoverFromPhysicsDisturbance();synchronizeExternalTarget();ControlAxis pulseAxis=manualPulseAxis;double pulseValue=manualPulseValue;manualPulseAxis=null;manualPulseValue=0.0D;Map<ControlAxis,Double> stabiliseCommands=Map.of();if(stabiliserEnabled){StabilizationSetpoint sp=StabilizationSetpoint.manualNudge(pitchStick,rollStick,yawRateStick,verticalStick,longitudinalStick,lateralStick,maxManualTiltRadians,maxManualYawRate,maxManualSpeed);applyHoldSetpoints(sp,state,!autopilotEnabled);stabiliseCommands=stabilizeStabilizer.computeCommands(state,sp,dt,registry,FlightMode.STABILIZE);stabiliseCommands=filterStabilizerAxes(stabiliseCommands);}else stabilizeStabilizer.resetAll();Map<ControlAxis,Double> autopilotCommands=Map.of();if(autopilotEnabled&&navigator.hasTarget()){ticksSinceReplan++;if(ticksSinceReplan>=Math.max(1,replanIntervalTicks)||navigator.distanceToTarget(state)<3.0){latestCruiseSetpoint=navigator.plan(state,cruiseMaxSpeed,estimateCruiseDeceleration(state));ticksSinceReplan=0;}StabilizationSetpoint sp=latestCruiseSetpoint.copy();double[] smoothVelocity=smoothCruiseVelocity(sp.desiredLongitudinalVelocity,sp.desiredLateralVelocity,dt);sp.desiredLongitudinalVelocity=smoothVelocity[0];sp.desiredLateralVelocity=smoothVelocity[1];if(altitudeHold&&Double.isFinite(altitudeHoldTargetY))sp.desiredVerticalVelocity=clamp((altitudeHoldTargetY-state.y)*HOLD_VERTICAL_P,-MAX_HOLD_VERTICAL_SPEED,MAX_HOLD_VERTICAL_SPEED);applyHoldSetpoints(sp,state,false);autopilotCommands=cruiseStabilizer.computeCommands(state,sp,dt,registry,FlightMode.CRUISE);if(stabiliserEnabled)autopilotCommands=filterAutopilotAxes(autopilotCommands);mode=FlightMode.CRUISE;}else{cruiseStabilizer.resetAll();ticksSinceReplan=0;lastCruiseLongitudinalVelocity=0;lastCruiseLateralVelocity=0;}if(pulseAxis!=null){if(autopilotEnabled)autopilotCommands=withAddedCommand(autopilotCommands,pulseAxis,pulseValue);else stabiliseCommands=withAddedCommand(stabiliseCommands,pulseAxis,pulseValue);}double recoveryScale=disturbanceRecoveryTicks>0?1-(.65*disturbanceRecoveryTicks/(double)DISTURBANCE_RECOVERY_TICKS):1;if(disturbanceRecoveryTicks>0)disturbanceRecoveryTicks--;recoveryScale=Math.max(.35,recoveryScale);if(recoveryScale<.999){stabiliseCommands=scaleCommands(stabiliseCommands,recoveryScale);autopilotCommands=scaleCommands(autopilotCommands,recoveryScale);}allocator.applyCombined(registry,state,stabiliseCommands,autopilotCommands);previousControlState=state.copy();}
    private static Map<ControlAxis,Double> withAddedCommand(Map<ControlAxis,Double> base,ControlAxis axis,double value){Map<ControlAxis,Double> result=new EnumMap<>(ControlAxis.class);if(base!=null)result.putAll(base);result.merge(axis,value,Double::sum);result.put(axis,clamp(result.get(axis),-1.0D,1.0D));return result;} private double[] smoothCruiseVelocity(double desiredLongitudinal,double desiredLateral,double dt){VehicleState state=stateProvider.getState();double mass=state==null?1.0:Math.max(1e-3,state.mass);double longitudinalAuthority=registry.getAxisAuthority(FlightMode.CRUISE,ControlAxis.LONGITUDINAL),lateralAuthority=registry.getAxisAuthority(FlightMode.CRUISE,ControlAxis.LATERAL);double maxAcceleration=Math.max(.25,Math.min(longitudinalAuthority,lateralAuthority)/mass),maxDelta=Math.max(.01,Math.min(.55,.30*maxAcceleration)*Math.max(dt,0));lastCruiseLongitudinalVelocity+=clamp(desiredLongitudinal-lastCruiseLongitudinalVelocity,-maxDelta,maxDelta);lastCruiseLateralVelocity+=clamp(desiredLateral-lastCruiseLateralVelocity,-maxDelta,maxDelta);return new double[]{lastCruiseLongitudinalVelocity,lastCruiseLateralVelocity};}
    private static double normalizeRadians(double a){double r=a%(Math.PI*2);if(r>Math.PI)r-=Math.PI*2;if(r<-Math.PI)r+=Math.PI*2;return r;} private boolean detectPhysicsDisturbance(VehicleState s){if(previousControlState==null)return false;double dp=Math.sqrt(sq(s.x-previousControlState.x)+sq(s.y-previousControlState.y)+sq(s.z-previousControlState.z)),dv=Math.sqrt(sq(s.vx-previousControlState.vx)+sq(s.vy-previousControlState.vy)+sq(s.vz-previousControlState.vz)),da=Math.sqrt(sq(s.pitchRate-previousControlState.pitchRate)+sq(s.yawRate-previousControlState.yawRate)+sq(s.rollRate-previousControlState.rollRate)),dang=Math.sqrt(sq(normalizeRadians(s.pitch-previousControlState.pitch))+sq(normalizeRadians(s.yaw-previousControlState.yaw))+sq(normalizeRadians(s.roll-previousControlState.roll)));return dp>DISTURBANCE_POSITION_DELTA||dv>DISTURBANCE_SPEED_DELTA||da>DISTURBANCE_ANGULAR_RATE_DELTA||dang>DISTURBANCE_ANGLE_DELTA;} private void recoverFromPhysicsDisturbance(){stabilizeStabilizer.resetAll();cruiseStabilizer.resetAll();allocator.hardStop();ticksSinceReplan=0;lastCruiseLongitudinalVelocity=0;lastCruiseLateralVelocity=0;latestCruiseSetpoint=StabilizationSetpoint.hover();disturbanceRecoveryTicks=DISTURBANCE_RECOVERY_TICKS;} private static double sq(double v){return v*v;}
    private static Map<ControlAxis,Double> scaleCommands(Map<ControlAxis,Double> m,double s){if(m==null||m.isEmpty())return Map.of();Map<ControlAxis,Double> r=new EnumMap<>(ControlAxis.class);for(Map.Entry<ControlAxis,Double> e:m.entrySet())r.put(e.getKey(),e.getValue()*s);return r;}
    private static Map<ControlAxis,Double> filterStabilizerAxes(Map<ControlAxis,Double> m){if(m==null||m.isEmpty())return Map.of();Map<ControlAxis,Double> r=new EnumMap<>(ControlAxis.class);for(Map.Entry<ControlAxis,Double> e:m.entrySet())if(e.getKey()==ControlAxis.PITCH||e.getKey()==ControlAxis.ROLL||e.getKey()==ControlAxis.VERTICAL)r.put(e.getKey(),e.getValue());return r;} private static Map<ControlAxis,Double> filterAutopilotAxes(Map<ControlAxis,Double> m){if(m==null||m.isEmpty())return Map.of();Map<ControlAxis,Double> r=new EnumMap<>(ControlAxis.class);for(Map.Entry<ControlAxis,Double> e:m.entrySet()){ControlAxis a=e.getKey();if(a==ControlAxis.VERTICAL||a==ControlAxis.LONGITUDINAL||a==ControlAxis.LATERAL||a==ControlAxis.YAW)r.put(a,e.getValue());}return r;}
    private void applyHoldSetpoints(StabilizationSetpoint sp,VehicleState s,boolean allowPosition){if(headingHold){sp.desiredYaw=holdYaw;sp.yawIsRateNotHeading=false;}if(positionHold&&allowPosition){double[] b=worldToBodyVelocity(holdX-s.x,holdZ-s.z,s.yaw);sp.desiredLongitudinalVelocity=clamp(b[0]*.85,-maxManualSpeed,maxManualSpeed);sp.desiredLateralVelocity=clamp(b[1]*.85,-maxManualSpeed,maxManualSpeed);}else if(velocityHold&&allowPosition){double[] b=worldToBodyVelocity(holdVx,holdVz,s.yaw);sp.desiredLongitudinalVelocity=clamp(b[0],-maxManualSpeed,maxManualSpeed);sp.desiredLateralVelocity=clamp(b[1],-maxManualSpeed,maxManualSpeed);}if(positionHold||altitudeHold)sp.desiredVerticalVelocity=clamp((holdY-s.y)*HOLD_VERTICAL_P,-MAX_HOLD_VERTICAL_SPEED,MAX_HOLD_VERTICAL_SPEED);else if(velocityHold)sp.desiredVerticalVelocity=clamp(holdVy,-MAX_HOLD_VERTICAL_SPEED,MAX_HOLD_VERTICAL_SPEED);}
    private static double[] worldToBodyVelocity(double vx,double vz,double yaw){double sinY=Math.sin(yaw),cosY=Math.cos(yaw);return new double[]{vx*sinY+vz*cosY,vx*cosY-vz*sinY};} private static double clamp(double v,double min,double max){return Math.max(min,Math.min(max,v));}
    private double estimateCruiseDeceleration(VehicleState s){double positive=registry.getVectorAuthority(FlightMode.CRUISE,VectorDirection.NORTH),negative=registry.getVectorAuthority(FlightMode.CRUISE,VectorDirection.SOUTH),east=registry.getVectorAuthority(FlightMode.CRUISE,VectorDirection.EAST),west=registry.getVectorAuthority(FlightMode.CRUISE,VectorDirection.WEST);double oneDirection=Math.max(.25,Math.max(Math.max(positive,negative),Math.max(east,west))/Math.max(s.mass,1e-3));return Math.max(.35,oneDirection*.55);}
}
