package com.flightcomputer.control;

import net.minecraft.world.phys.Vec3;
import org.joml.Matrix3dc;
import org.joml.Vector3dc;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Map;

/** Server-side reflective bridge to Sable's authoritative mass, inertia and force state. */
public final class SableDynamicsReader {
    private SableDynamicsReader() { }
    public static boolean readMassData(Object subLevel,VehicleState state,Vec3 controllerLocalCenter){
        if(subLevel==null||state==null)return false;try{Method gm=findMethod(subLevel.getClass(),"getMassTracker");if(gm==null)return false;Object data=gm.invoke(subLevel);if(data==null)return false;boolean changed=false;
            Object mass=invokeNoArg(data,"getMass");if(mass instanceof Number n&&Double.isFinite(n.doubleValue())&&n.doubleValue()>0){state.mass=n.doubleValue();changed=true;}
            Object blocks=invokeNoArg(data,"getBlockCount","getMassBlockCount","getStructureBlockCount","getPartCount","getBlockAmount");if(blocks instanceof Number n&&n.intValue()>=0)state.structureBlockCount=n.intValue();
            Object center=invokeNoArg(data,"getCenterOfMass");if(center instanceof Vector3dc com){double cx=com.x()-(controllerLocalCenter==null?0:controllerLocalCenter.x),cy=com.y()-(controllerLocalCenter==null?0:controllerLocalCenter.y),cz=com.z()-(controllerLocalCenter==null?0:controllerLocalCenter.z);if(finite(cx)&&finite(cy)&&finite(cz)){state.comX=cx;state.comY=cy;state.comZ=cz;changed=true;}}
            Object inertia=invokeNoArg(data,"getInertiaTensor");if(inertia instanceof Matrix3dc matrix){copyMatrix(matrix,state);state.inertiaPitch=Math.max(1e-3,Math.abs(matrix.m00()));state.inertiaRoll=Math.max(1e-3,Math.abs(matrix.m22()));state.inertiaYaw=Math.max(1e-3,Math.abs(matrix.m11()));changed=true;}return changed;
        }catch(ReflectiveOperationException|RuntimeException|LinkageError ignored){return false;}
    }
    public static void readPhysicsPanel(Object subLevel,VehicleState state){if(subLevel==null||state==null)return;state.gravityAcceleration=readScalar(subLevel,"getGravityAcceleration","getGravity","gravity","getGravityScale");double[] v;
        v=readVector(subLevel,"getDragForce","getDrag","dragForce");state.dragForceX=v[0];state.dragForceY=v[1];state.dragForceZ=v[2];v=readVector(subLevel,"getLevitationForce","getLevitation","levitationForce");state.levitationForceX=v[0];state.levitationForceY=v[1];state.levitationForceZ=v[2];v=readVector(subLevel,"getBalloonLiftForce","getBalloonLift","balloonLiftForce");state.balloonLiftForceX=v[0];state.balloonLiftForceY=v[1];state.balloonLiftForceZ=v[2];v=readVector(subLevel,"getPropulsionForce","getPropulsion","propulsionForce");state.propulsionForceX=v[0];state.propulsionForceY=v[1];state.propulsionForceZ=v[2];v=readVector(subLevel,"getLiftForce","getLift","liftForce");state.liftForceX=v[0];state.liftForceY=v[1];state.liftForceZ=v[2];v=readVector(subLevel,"getMagneticForce","getMagnetic","magneticForce");state.magneticForceX=v[0];state.magneticForceY=v[1];state.magneticForceZ=v[2];v=readVector(subLevel,"getRecoilForce","getRecoil","recoilForce");state.recoilForceX=v[0];state.recoilForceY=v[1];state.recoilForceZ=v[2];v=readVector(subLevel,"getImpactForce","getImpact","impactForce");state.impactForceX=v[0];state.impactForceY=v[1];state.impactForceZ=v[2];
        Object panel=invokeNoArg(subLevel,"getPhysicsState","getPhysics","getForces","getForceState");if(panel!=null){state.gravityAcceleration=prefer(readScalar(panel,"getGravityAcceleration","getGravity","gravity","getGravityScale"),state.gravityAcceleration);double[] p;p=prefer(readVector(panel,"getDragForce","getDrag","dragForce"),state.dragForceX,state.dragForceY,state.dragForceZ);state.dragForceX=p[0];state.dragForceY=p[1];state.dragForceZ=p[2];p=prefer(readVector(panel,"getLevitationForce","getLevitation","levitationForce"),state.levitationForceX,state.levitationForceY,state.levitationForceZ);state.levitationForceX=p[0];state.levitationForceY=p[1];state.levitationForceZ=p[2];p=prefer(readVector(panel,"getBalloonLiftForce","getBalloonLift","balloonLiftForce"),state.balloonLiftForceX,state.balloonLiftForceY,state.balloonLiftForceZ);state.balloonLiftForceX=p[0];state.balloonLiftForceY=p[1];state.balloonLiftForceZ=p[2];p=prefer(readVector(panel,"getPropulsionForce","getPropulsion","propulsionForce"),state.propulsionForceX,state.propulsionForceY,state.propulsionForceZ);state.propulsionForceX=p[0];state.propulsionForceY=p[1];state.propulsionForceZ=p[2];p=prefer(readVector(panel,"getLiftForce","getLift","liftForce"),state.liftForceX,state.liftForceY,state.liftForceZ);state.liftForceX=p[0];state.liftForceY=p[1];state.liftForceZ=p[2];p=prefer(readVector(panel,"getMagneticForce","getMagnetic","magneticForce"),state.magneticForceX,state.magneticForceY,state.magneticForceZ);state.magneticForceX=p[0];state.magneticForceY=p[1];state.magneticForceZ=p[2];p=prefer(readVector(panel,"getRecoilForce","getRecoil","recoilForce"),state.recoilForceX,state.recoilForceY,state.recoilForceZ);state.recoilForceX=p[0];state.recoilForceY=p[1];state.recoilForceZ=p[2];p=prefer(readVector(panel,"getImpactForce","getImpact","impactForce"),state.impactForceX,state.impactForceY,state.impactForceZ);state.impactForceX=p[0];state.impactForceY=p[1];state.impactForceZ=p[2];}}
    public static double[] queuedForceAndTorque(Object subLevel){double[] r=new double[6];if(subLevel==null)return r;try{Method m=findMethod(subLevel.getClass(),"getQueuedForceGroups");if(m==null)return r;Object groups=m.invoke(subLevel);if(!(groups instanceof Map<?,?> map))return r;for(Map.Entry<?,?> e:map.entrySet()){Object total=invokeNoArg(e.getValue(),"getForceTotal");if(total==null)continue;Object f=invokeNoArg(total,"getLocalForce"),t=invokeNoArg(total,"getLocalTorque");if(f instanceof Vector3dc v){r[0]+=v.x();r[1]+=v.y();r[2]+=v.z();}if(t instanceof Vector3dc v){r[3]+=v.x();r[4]+=v.y();r[5]+=v.z();}}}catch(ReflectiveOperationException|RuntimeException|LinkageError ignored){}return r;}
    private static double readScalar(Object target,String...names){for(String name:names){Object v=invokeNoArg(target,name);if(v instanceof Number n&&Double.isFinite(n.doubleValue()))return n.doubleValue();}return 0;}
    private static double prefer(double v,double old){return Math.abs(v)>1e-12?v:old;}
    private static double[] prefer(double[] v,double x,double y,double z){return Math.abs(v[0])+Math.abs(v[1])+Math.abs(v[2])>1e-12?v:new double[]{x,y,z};}
    private static double[] readVector(Object target,String...names){for(String name:names){double[] v=toVector(invokeNoArg(target,name));if(v!=null)return v;}return new double[3];}
    private static double[] toVector(Object value){if(value instanceof Vector3dc v)return new double[]{v.x(),v.y(),v.z()};if(value instanceof Vec3 v)return new double[]{v.x,v.y,v.z};if(value instanceof Number n)return new double[]{0,n.doubleValue(),0};if(value==null)return null;Double x=component(value,"x","getX"),y=component(value,"y","getY"),z=component(value,"z","getZ");return x!=null&&y!=null&&z!=null?new double[]{x,y,z}:null;}
    private static Double component(Object target,String field,String getter){try{Field f=findField(target.getClass(),field);if(f!=null&&f.get(target) instanceof Number n)return n.doubleValue();}catch(ReflectiveOperationException|RuntimeException ignored){}Object v=invokeNoArg(target,getter);return v instanceof Number n?n.doubleValue():null;}
    private static void copyMatrix(Matrix3dc m,VehicleState s){s.i00=finite(m.m00())?m.m00():1;s.i01=finite(m.m01())?m.m01():0;s.i02=finite(m.m02())?m.m02():0;s.i10=finite(m.m10())?m.m10():0;s.i11=finite(m.m11())?m.m11():1;s.i12=finite(m.m12())?m.m12():0;s.i20=finite(m.m20())?m.m20():0;s.i21=finite(m.m21())?m.m21():0;s.i22=finite(m.m22())?m.m22():1;}
    private static Method findMethod(Class<?> type,String name){Class<?> c=type;while(c!=null){try{Method m=c.getDeclaredMethod(name);m.setAccessible(true);return m;}catch(ReflectiveOperationException|RuntimeException ignored){c=c.getSuperclass();}}try{Method m=type.getMethod(name);m.setAccessible(true);return m;}catch(ReflectiveOperationException|RuntimeException ignored){return null;}}
    private static Object invokeNoArg(Object target,String...names){if(target==null)return null;for(String name:names){Method m=findMethod(target.getClass(),name);if(m==null)continue;try{return m.invoke(target);}catch(ReflectiveOperationException|RuntimeException ignored){}}return null;}
    private static Field findField(Class<?> type,String name){Class<?> c=type;while(c!=null){try{Field f=c.getDeclaredField(name);f.setAccessible(true);return f;}catch(ReflectiveOperationException|RuntimeException ignored){c=c.getSuperclass();}}return null;}
    private static boolean finite(double v){return Double.isFinite(v);}
}
