package com.flightcomputer.client.gui;

import com.flightcomputer.avionics.ThermalState;
import com.flightcomputer.block.FlightControllerBlockEntity;
import com.flightcomputer.client.FlightComputerTelemetryClient;
import com.flightcomputer.network.FlightComputerNetwork;
import com.flightcomputer.item.CoolingUpgradeItem;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.entity.BlockEntity;

/** Dedicated thermal tab surface for the Flight Computer overlay. */
public final class ThermalConsoleScreen extends Screen {
    private static final int PANEL = 0xE610141A;
    private static final int TEXT = 0xFFE6EEF2;
    private static final int MUTED = 0xFF9DAEB5;
    private static final int CYAN = 0xFF66D9FF;
    private static final int GREEN = 0xFF55FF55;
    private static final int AMBER = 0xFFFFCC55;
    private static final int RED = 0xFFFF5555;

    private final BlockPos controllerPos;
    private FlightControllerBlockEntity controller;
    private int left;
    private int top;

    public ThermalConsoleScreen(BlockPos controllerPos) {
        super(Component.literal("Flight Computer - Thermal"));
        this.controllerPos = controllerPos;
    }

    @Override
    protected void init() {
        controller = getController();
        left = Math.max(10, (width - 640) / 2);
        top = Math.max(20, (height - 360) / 2);
        addRenderableWidget(Button.builder(Component.literal("NAVIGATION"), b -> minecraft.setScreen(new NavigationConsoleScreen(controllerPos)))
                .bounds(left, top, 150, 22).build());
        addRenderableWidget(Button.builder(Component.literal("THERMAL"), b -> {})
                .bounds(left + 160, top, 150, 22).build());
        addRenderableWidget(Button.builder(Component.literal("CLOSE"), b -> onClose())
                .bounds(left + 490, top, 150, 22).build());
    }

    private FlightControllerBlockEntity getController() {
        if (minecraft == null || minecraft.level == null) return null;
        BlockEntity be = minecraft.level.getBlockEntity(controllerPos);
        return be instanceof FlightControllerBlockEntity fc ? fc : null;
    }

    @Override
    public void tick() {
        super.tick();
        controller = getController();
        if (controller == null) { onClose(); }
    }

    @Override
    public void render(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
        int right = left + 640;
        int bottom = top + 340;
        g.fill(left - 8, top - 8, right + 8, bottom + 8, PANEL);
        g.drawString(font, "◈ FLIGHT COMPUTER / THERMAL MANAGEMENT", left, top - 2, TEXT);

        double temperature = controller == null ? 0.0D : controller.getTemperature();
        double maximum = controller == null ? 1.0D : Math.max(1.0D, controller.getMaxTemperature());
        double ratio = Math.max(0.0D, Math.min(1.0D, temperature / maximum));
        ThermalState state = controller == null ? ThermalState.NORMAL : controller.getThermalState();
        int stateColor = state == ThermalState.THERMAL_SHUTDOWN || state == ThermalState.CRITICAL ? RED : state == ThermalState.HOT ? AMBER : GREEN;

        g.drawString(font, "THERMAL STATUS", left + 20, top + 48, TEXT);
        g.drawString(font, state.name().replace('_', ' '), left + 250, top + 48, stateColor);
        g.drawString(font, String.format("TEMPERATURE  %.1f / %.1f", temperature, maximum), left + 20, top + 76, TEXT);
        g.fill(left + 20, top + 94, left + 620, top + 112, 0xFF20272C);
        int bar = (int)(600 * ratio);
        g.fill(left + 20, top + 94, left + 20 + bar, top + 112, stateColor);
        g.drawString(font, String.format("%.1f%%", ratio * 100.0D), left + 285, top + 98, TEXT);

        int cooldown = controller == null ? 0 : controller.getThermalCooldownTicksRemaining();
        g.drawString(font, cooldown > 0 ? String.format("COOLDOWN LOCKOUT: %.1f s", cooldown / 20.0D) : "COOLDOWN LOCKOUT: CLEAR", left + 20, top + 132, cooldown > 0 ? RED : GREEN);
        g.drawString(font, "Cooling upgrades", left + 20, top + 164, CYAN);
        g.drawString(font, "Insert a cooling module with it in your main hand. Click an occupied slot with an empty hand to remove it.", left + 20, top + 184, MUTED);

        for (int slot = 0; slot < 3; slot++) renderSlot(g, slot);
        g.drawString(font, "SYSTEM RESPONSE", left + 20, top + 250, CYAN);
        g.drawString(font, "Thermal load is generated by controller operation and propulsion control; cooling reduces temperature continuously.", left + 20, top + 270, MUTED);
        g.drawString(font, "THERMAL SHUTDOWN prevents operation until the controller has cooled below the recovery threshold.", left + 20, top + 288, MUTED);

        var snapshot = controller == null ? null : FlightComputerTelemetryClient.get(controller.getControllerId());
        if (snapshot != null) {
            g.drawString(font, "TELEMETRY: " + thermalName(snapshot.thermalState()) + " | COOLING TIER " + snapshot.coolingTier(), left + 20, top + 314, TEXT);
        }

        super.render(g, mouseX, mouseY, partialTick);
        g.fill(left + 160, top + 20, left + 310, top + 22, CYAN);
    }

    private void renderSlot(GuiGraphics g, int slot) {
        int x = left + 150 + slot * 70;
        int y = top + 200;
        g.fill(x, y, x + 52, y + 52, 0xFF0D1114);
        g.fill(x, y, x + 52, y + 2, CYAN);
        ItemStack stack = controller == null ? ItemStack.EMPTY : controller.getUpgradeHandler().getStackInSlot(slot);
        if (!stack.isEmpty()) {
            g.renderItem(stack, x + 18, y + 10);
            g.renderItemDecorations(font, stack, x + 18, y + 10);
        } else {
            g.drawString(font, "+", x + 22, y + 17, MUTED);
        }
        g.drawString(font, Integer.toString(slot + 1), x + 23, y + 39, MUTED);
    }

    @Override
    public boolean mouseClicked(double mouseX, double mouseY, int button) {
        if (button == 0 && controller != null) {
            for (int slot = 0; slot < 3; slot++) {
                int x = left + 150 + slot * 70;
                int y = top + 200;
                if (mouseX >= x && mouseX <= x + 52 && mouseY >= y && mouseY <= y + 52) {
                    ItemStack hand = minecraft.player == null ? ItemStack.EMPTY : minecraft.player.getMainHandItem();
                    FlightComputerNetwork.sendCoolingSlot(controllerPos, slot, hand.isEmpty() ? 1 : 0);
                    return true;
                }
            }
        }
        return super.mouseClicked(mouseX, mouseY, button);
    }

    private static String thermalName(int id) {
        return switch (id) {
            case 1 -> "WARM";
            case 2 -> "HOT";
            case 3 -> "CRITICAL";
            case 4 -> "THERMAL SHUTDOWN";
            default -> "NORMAL";
        };
    }

    @Override public void renderBackground(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) { }
    @Override public boolean isPauseScreen() { return false; }
}
